[deps]
AirspeedVelocity = "1c8270ee-6884-45cc-9545-60fa71ec23e4"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
Siphon = "4bbcb006-69a8-46c4-bd0b-6b150ee03dfc"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[sources]
Siphon = {path = ".."}

[compat]
AirspeedVelocity = "0.6"
BenchmarkTools = "1"
StableRNGs = "1"
