name = "Siphon"
uuid = "4bbcb006-69a8-46c4-bd0b-6b150ee03dfc"
version = "0.1.0"
author = "Giuseppe Ragusa <giuseppe.ragusa@gmail.com>"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"

[compat]
Aqua = "0.8"
CSV = "0.10"
DataFrames = "1"
ForwardDiff = "1"
LinearAlgebra = "1.10"
LogDensityProblems = "2"
Optimization = "5"
OptimizationOptimJL = "0.4"
Random = "1.10"
RecipesBase = "1.3"
StaticArrays = "1"
Statistics = "1.10"
Test = "1.10"
TestItemRunner = "1"
TestItems = "1"
TransformVariables = "0.8"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[targets]
test = ["Aqua", "Test", "CSV", "DataFrames", "Random", "RecipesBase", "TestItems", "TestItemRunner"]
